
big_billion_cars.dbconnection.username = "postgres"
big_billion_cars.dbconnection.password="12345"
big_billion_cars.dbconnection.dbHost="localhost"
big_billion_cars.dbconnection.port=5432
big_billion_cars.dbconnection.database="postgres"

big_billion_cars.dbconnection.acesKeyId="xxxxxxxxxxxxxxx"
big_billion_cars.dbconnection.secretAcesKey="xxxxxxxxxxx"

big_billion_cars.dbconnection.mail="yudhistervijay@gmail.com"
big_billion_cars.dbconnection.mailSmtpPassword="xxxxxxxxxxxx"
